### PR TITLE
OCPBUGS-6538: go.mod: update github.com/prometheus/client_golang to v1.11.0

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

### CODE REVIEW

**Comment by simonpasquier** [comment]
should we take the opportunity to bump to https://github.com/jimmidyson/configmap-reload/tree/v0.8.0?

**Comment by jan--f** [comment]
> should we take the opportunity to bump to https://github.com/jimmidyson/configmap-reload/tree/v0.8.0?

For `release-4.10`?

**Comment by simonpasquier** [comment]
ah I missed that it was for a release branch :facepalm: 

/lgtm
/label backport-risk-assessed

**Comment by juzhao** [comment]
tested with PR, no regression issues for config-reloader
/label cherry-pick-approved

**Pull request merged**
