### PR TITLE
Bug 2067745: upgrade module github.com/prometheus/client_golang to v1.12.2.

### PR DESCRIPTION
**Pull request by raptorsun**
This PR resolves bug 2067745 by upgrading module github.com/prometheus/client_golang to v1.12.2.

### CODE REVIEW

**Comment by raptorsun** [comment]
@simonpasquier Bugfix is ready :)

**Comment by simonpasquier** [comment]
could you propose the change upstream (e.g. https://github.com/jimmidyson/configmap-reload)?

**Comment by raptorsun** [comment]
> could you propose the change upstream (e.g. https://github.com/jimmidyson/configmap-reload)?

of course, PR has been created https://github.com/jimmidyson/configmap-reload/pull/72

**Comment by simonpasquier** [comment]
Please merge the upstream master branch in this repository.

**Comment by raptorsun** [comment]
> Please merge the upstream master branch in this repository.

PR is created for merging upstream master branch, bringing many more commit than this fix:  https://github.com/openshift/configmap-reload/pull/44

**Pull request closed without merging**
