### PR TITLE
*: fix repository ownership

### PR DESCRIPTION
**Pull request by paulfantom**
/cc @openshift/openshift-team-monitoring-maintainers

### CODE REVIEW

**Comment by s-urbaniak** [comment]
we should think about some automation here too :thinking:

**Comment by paulfantom** [comment]
> we should think about some automation here too

Prow cannot handle github groups right now so the only thing would be to write an automatic reconciling of one file across multiple repositories. Similar to the thing I wrote for prometheus Makefile.common in https://github.com/prometheus/prometheus/pull/5444. But that would mean we need to enable travis on repo which would be our source of truth.

Or add option to prow bot :smile: Issue is still open at https://github.com/kubernetes/test-infra/issues/10065

**Pull request merged**
